name: deploy-to-oci

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: hw-rui-server-image
  DOCKER_CONTAINER_NAME: hw-rui-server-container
  SERVER_CONFIG: ${{ secrets.SERVER_CONFIG }}

jobs:
  warmup:
    runs-on: hw-oci-runner
    steps:
      - name: Testing SERVER_CONFIG
        run: echo ${{ secrets.SERVER_CONFIG }}
      - name: Testing SERVER_CONFIG(declared local scope)
        run: echo $SERVER_CONFIG
      - name: Testing self-hosted runner, check user.
        run: whoami
      - name: check executable docker cli
        run: docker --version

  # docker-build:
  #   needs: warmup
  #   runs-on: hw-oci-runner
  #   environment: ${{ vars.CI_CONFIG }}
  #   steps:
  #     - name: Testing CI_CONFIG.SERVER_CONFIG
  #       run: echo "$SERVER_CONFIG"
  #     - name: Git Checkout and check exist dockerfile.
  #       uses: actions/checkout@v4
  #     - name: Build docker image.
  #       run: docker build -t $DOCKER_IMAGE_NAME .
  #     - name: Check created image.
  #       run: docker images

  # docker-container-run:
  #   needs: docker-build
  #   runs-on: hw-oci-runner
  #   steps:
  #     - name: Run docker container from create image.
  #       run: docker run -it -d -p 8000:8001 --name $DOCKER_CONTAINER_NAME $DOCKER_IMAGE_NAME
