name: deploy-to-oci
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: hw-oci-runner
    steps:
      - name: Testing self-hosted runner
        run:
          - whoami
          - sudo docker --version
