name: deploy-to-oci

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_NAME: hw-rui-server-image
  DOCKER_CONTAINER_NAME: hw-rui-server-container
  SERVER_CONFIG: ${{secrets.SERVER_CONFIG}}
jobs:
  warmup:
    runs-on: hw-oci-runner
    steps:
      - name: Testing self-hosted runner, check user.
        run: whoami
      - name: check executable docker cli
        run: docker --version

  docker-build:
    needs: warmup
    runs-on: hw-oci-runner
    steps:
      - name: Git Checkout and check exist dockerfile.
        uses: actions/checkout@v4
      - name: Build docker image.
        run: docker build -t $DOCKER_IMAGE_NAME --build-arg SERVER_CONFIG=$SERVER_CONFIG --no-cache .
      - name: Check created image.
        run: docker images
      - name: Exporting HOST_APP_PORT.
        run: source ./export-host-app-port.sh
      - name: Check exported HOST_APP_PORT.
        run: echo $HOST_APP_PORT
      - name: docker run -it -d -p $HOST_APP_PORT:8001 --name $DOCKER_CONTAINER_NAME $DOCKER_IMAGE_NAME

  # docker-container-run:
  #   needs: docker-build
  #   runs-on: hw-oci-runner
  #   steps:
  #     - name: Run docker container from create image.
  #       run: docker run -it -d -p 8000:8001 --name $DOCKER_CONTAINER_NAME $DOCKER_IMAGE_NAME
